class WebTitles:
    titles = {
    # Соцсети и мессенджеры (Font Awesome)
    "youtube.com": 'YouTube',
    "youtu.be": 'YouTube',
    "tiktok.com": 'TikTok',
    "tiktok.io": 'TikTok',
    "instagram.com": 'Instagram',
    "facebook.com": 'Facebook',
    "fb.com": 'Facebook',
    "twitter.com": 'Twitter',
    "x.com": 'X (Twitter)',
    "reddit.com": 'Reddit',
    "pinterest.com": 'Pinterest',
    "linkedin.com": 'LinkedIn',
    "vk.com": 'ВКонтакте',
    "ok.ru": 'Одноклассники',
    "t.me": 'Telegram',
    "telegram.org": 'Telegram',
    "discord.com": 'Discord',
    "discord.gg": 'Discord',
    "whatsapp.com": 'WhatsApp',
    "wa.me": 'WhatsApp',
    "snapchat.com": 'Snapchat',
    "twitch.tv": 'Twitch',
    "tumblr.com": 'Tumblr',
    
    # Видео и стриминг (Font Awesome)
    "netflix.com": 'Netflix',
    "hbomax.com": 'HBO Max',
    "disneyplus.com": 'Disney+',
    "primevideo.com": 'Amazon Prime Video',
    "crunchyroll.com": 'Crunchyroll',
    "vimeo.com": 'Vimeo',
    "dailymotion.com": 'Dailymotion',
    "rutube.ru": 'Rutube',
    "ivi.ru": 'Иви',
    "start.ru": 'Start',
    "okko.tv": 'Okko',
    "more.tv": 'More.tv',
    
    # Музыка и подкасты (Font Awesome)
    "spotify.com": 'Spotify',
    "music.yandex.ru": 'Яндекс Музыка',
    "music.youtube.com": 'YouTube Music',
    "deezer.com": 'Deezer',
    "soundcloud.com": 'SoundCloud',
    "apple.com/music": 'Apple Music',
    "bandcamp.com": 'Bandcamp',
    "shazam.com": 'Shazam',
    "last.fm": 'Last.fm',
    
    # Поисковики и браузеры (Font Awesome)
    "google.com": 'Google',
    "yandex.ru": 'Яндекс',
    "yahoo.com": 'Yahoo',
    "bing.com": 'Bing',
    "duckduckgo.com": 'DuckDuckGo',
    "baidu.com": 'Baidu',
    "opera.com": 'Opera',
    "brave.com": 'Brave',
    
    # Почта (Font Awesome)
    "gmail.com": 'Gmail',
    "mail.google.com": 'Gmail',
    "outlook.com": 'Outlook',
    "hotmail.com": 'Outlook',
    "yahoo.com/mail": 'Yahoo Mail',
    "mail.yandex.ru": 'Яндекс Почта',
    "mail.ru": 'Mail.ru',
    "protonmail.com": 'ProtonMail',
    "zoho.com/mail": 'Zoho Mail',
    
    # Облака и хранилища (Font Awesome)
    "drive.google.com": 'Google Диск',
    "dropbox.com": 'Dropbox',
    "mega.nz": 'MEGA',
    "onedrive.live.com": 'OneDrive',
    "icloud.com": 'iCloud',
    "disk.yandex.ru": 'Яндекс Диск',
    "cloud.mail.ru": 'Облако Mail.ru',
    
    # Разработка и IT (Font Awesome)
    "github.com": 'GitHub',
    "gitlab.com": 'GitLab',
    "bitbucket.org": 'Bitbucket',
    "stackoverflow.com": 'Stack Overflow',
    "stackexchange.com": 'Stack Exchange',
    "codepen.io": 'CodePen',
    "replit.com": 'Replit',
    "jsfiddle.net": 'JSFiddle',
    "docker.com": 'Docker',
    "kubernetes.io": 'Kubernetes',
    "digitalocean.com": 'DigitalOcean',
    "aws.amazon.com": 'AWS',
    "azure.microsoft.com": 'Azure',
    
    # Магазины и коммерция (Font Awesome)
    "amazon.com": 'Amazon',
    "amazon.ru": 'Amazon',
    "aliexpress.com": 'AliExpress',
    "aliexpress.ru": 'AliExpress',
    "ozon.ru": 'Ozon',
    "wildberries.ru": 'Wildberries',
    "yandex.ru/market": 'Яндекс Маркет',
    "ebay.com": 'eBay',
    "steampowered.com": 'Steam',
    "store.steampowered.com": 'Steam',
    "epicgames.com": 'Epic Games',
    "gog.com": 'GOG',
    "origin.com": 'Origin',
    "play.google.com/store": 'Google Play',
    "appstore.com": 'App Store',
    
    # Новости и медиа (Font Awesome)
    "bbc.com": 'BBC',
    "cnn.com": 'CNN',
    "nytimes.com": 'New York Times',
    "theguardian.com": 'The Guardian',
    "washingtonpost.com": 'Washington Post',
    "rt.com": 'RT',
    "rbc.ru": 'РБК',
    "lenta.ru": 'Лента.ру',
    "ria.ru": 'РИА Новости',
    "tass.ru": 'ТАСС',
    "meduza.io": 'Медуза',
    
    # Образование (Font Awesome)
    "coursera.org": 'Coursera',
    "udemy.com": 'Udemy',
    "stepik.org": 'Stepik',
    "khanacademy.org": 'Khan Academy',
    "edx.org": 'edX',
    "duolingo.com": 'Duolingo',
    "lingualeo.com": 'Lingualeo',
    "habr.com": 'Habr',
    "geeksforgeeks.org": 'GeeksforGeeks',
    "w3schools.com": 'W3Schools',
    "mdn.io": 'MDN Web Docs',
    
    # Переводчики и словари
    "translate.google.com": 'Google Переводчик',
    "translate.yandex.ru": 'Яндекс Переводчик',
    "reverso.net": 'Reverso Context',
    "deepl.com/translator": 'DeepL',
    "lingvo.ru": 'ABBYY Lingvo',
    "multitran.ru": 'Multitran',
    "wiktionary.org": 'Викисловарь',
    
    # Карты и навигация
    "maps.google.com": 'Google Карты',
    "yandex.ru/maps": 'Яндекс Карты',
    "2gis.ru": '2ГИС',
    "openstreetmap.org": 'OpenStreetMap',
    
    # Работа и фриланс
    "hh.ru": 'HeadHunter',
    "hh.ua": 'HeadHunter',
    "hh.kz": 'HeadHunter',
    "rabota.ru": 'Работа.ру',
    "superjob.ru": 'SuperJob',
    "freelance.ru": 'Freelance.ru',
    "upwork.com": 'Upwork',
    "fiverr.com": 'Fiverr',
    "fl.ru": 'FL.ru',
    
    # Банки и финансы
    "sberbank.ru": 'Сбербанк',
    "tinkoff.ru": 'Тинькофф',
    "vtb.ru": 'ВТБ',
    "alfabank.ru": 'Альфа-Банк',
    "raiffeisen.ru": 'Райффайзенбанк',
    "paypal.com": 'PayPal',
    "wise.com": 'Wise',
    "revolut.com": 'Revolut',
    "binance.com": 'Binance',
    
    # Еда и доставка
    "yandex.ru/eda": 'Яндекс Еда',
    "delivery-club.ru": 'Delivery Club',
    "sbermarket.ru": 'СберМаркет',
    "dodopizza.ru": 'Dodo Pizza',
    "mcdonalds.ru": 'McDonald\'s',
    "kfc.ru": 'KFC',
    "burgerking.ru": 'Burger King',
    "subway.com": 'Subway',
    
    # Путешествия
    "aviasales.ru": 'Aviasales',
    "tutu.ru": 'Tutu.ru',
    "ozon.ru/travel": 'Ozon Travel',
    "booking.com": 'Booking.com',
    "airbnb.com": 'Airbnb',
    "trivago.com": 'Trivago',
    "tripadvisor.com": 'Tripadvisor',
    
    # Государственные услуги (РФ)
    "gosuslugi.ru": 'Госуслуги',
    "nalog.gov.ru": 'Налоговая',
    "pfr.gov.ru": 'ПФР',
    "fssp.gov.ru": 'ФССП',
    "gibdd.ru": 'ГИБДД',
    
    # Русские сервисы
    "kinopoisk.ru": 'Кинопоиск',
    "tvzavr.ru": 'TVzavr',
    "amediateka.ru": 'Амедиатека',
    "megogo.ru": 'MEGOGO',
    "litres.ru": 'Литрес',
    "mybook.ru": 'MyBook',
    "chitai-gorod.ru": 'Читай-город',
    "labirint.ru": 'Лабиринт',
    "drom.ru": 'Drom.ru',
    "auto.ru": 'Auto.ru',
    "avito.ru": 'Avito',
    "cian.ru": 'ЦИАН',
    "turbotext.ru": 'ТурбоТекст',
    "advego.ru": 'Адвего',
    "etxt.ru": 'eTXT',
    "text.ru": 'Text.ru',
    
    # Другое
    "wikipedia.org": 'Wikipedia',
    "wikimedia.org": 'Wikimedia',
    "imdb.com": 'IMDb',
    "rottentomatoes.com": 'Rotten Tomatoes',
    "metacritic.com": 'Metacritic',
    "genius.com": 'Genius',
    "chess.com": 'Chess.com',
    "lichess.org": 'Lichess',
    "notion.so": 'Notion',
    "trello.com": 'Trello',
    "figma.com": 'Figma',
    "canva.com": 'Canva',
    "zoom.us": 'Zoom',
    "slack.com": 'Slack',
    "teams.microsoft.com": 'Microsoft Teams',
    "calendar.google.com": 'Google Calendar',
    "docs.google.com": 'Google Docs',
    "sheets.google.com": 'Google Sheets',
    "patreon.com": 'Patreon',
    "boosty.to": 'Boosty',

    # ===== ДОПОЛНЕНИЯ ИЗ FONT AWESOME BRANDS =====
    
    # A
    "500px.com": '500px',
    "accessible.org": 'Accessible Icon',
    "accusoft.com": 'Accusoft',
    "adn.by": 'ADN',
    "adversal.com": 'Adversal',
    "affiliatetheme.com": 'AffiliateTheme',
    "airbnb.com": 'Airbnb',
    "algolia.com": 'Algolia',
    "alipay.com": 'Alipay',
    "amilia.com": 'Amilia',
    "android.com": 'Android',
    "angellist.com": 'AngelList',
    "angrycreative.com": 'Angry Creative',
    "angular.io": 'Angular',
    "appstore.com": 'App Store',
    "apper.com": 'Apper',
    "apple.com": 'Apple',
    "artstation.com": 'ArtStation',
    "asymmetrik.com": 'Asymmetrik',
    "atlassian.com": 'Atlassian',
    "audible.com": 'Audible',
    "autoprefixer.github.io": 'Autoprefixer',
    "avianex.com": 'Aviadex',
    "aviato.com": 'Aviato',
    
    # B
    "battle.net": 'Battle.net',
    "behance.net": 'Behance',
    "bimobject.com": 'BIMobject',
    "bitcoin.org": 'Bitcoin',
    "bity.com": 'Bity',
    "blacktie.io": 'BlackTie',
    "blackberry.com": 'BlackBerry',
    "blogger.com": 'Blogger',
    "bluetooth.com": 'Bluetooth',
    "bootstrap.com": 'Bootstrap',
    "buffer.com": 'Buffer',
    "buromobelexperte.de": 'Buromobelexperte',
    "buysellads.com": 'BuySellAds',
    
    # C
    "canadianmapleleaf.com": 'Canadian Maple Leaf',
    "cc.com": 'Creative Commons',
    "centercode.com": 'Centercode',
    "centos.org": 'CentOS',
    "chrome.com": 'Chrome',
    "chromecast.com": 'Chromecast',
    "cloudflare.com": 'Cloudflare',
    "cloudscale.ch": 'Cloudscale',
    "cloudsmith.io": 'Cloudsmith',
    "cloudversify.com": 'Cloudversify',
    "codiepie.com": 'CodiePie',
    "confluence.com": 'Confluence',
    "connectdevelop.com": 'Connect Develop',
    "contao.org": 'Contao',
    "cottonbureau.com": 'Cotton Bureau',
    "cpanel.com": 'cPanel',
    "creativecommons.org": 'Creative Commons',
    "criticalrole.com": 'Critical Role',
    "css3.info": 'CSS3',
    "cuttlefish.io": 'Cuttlefish',
    
    # D
    "dnd.com": 'D&D',
    "dndbeyond.com": 'D&D Beyond',
    "dashcube.com": 'Dashcube',
    "delicious.com": 'Delicious',
    "deploydog.com": 'Deploydog',
    "deskpro.com": 'Deskpro',
    "dev.to": 'DEV',
    "deviantart.com": 'DeviantArt',
    "dhl.com": 'DHL',
    "diasporafoundation.org": 'Diaspora',
    "digg.com": 'Digg',
    "discourse.org": 'Discourse',
    "dochub.com": 'DocHub',
    "draft2digital.com": 'Draft2Digital',
    "dribbble.com": 'Dribbble',
    "drupal.org": 'Drupal',
    "dyalog.com": 'Dyalog',
    
    # E
    "earlybirds.com": 'Earlybirds',
    "edge.com": 'Microsoft Edge',
    "elementor.com": 'Elementor',
    "ello.co": 'Ello',
    "emberjs.com": 'Ember.js',
    "empireonline.com": 'Empire',
    "envira.com": 'Envira Gallery',
    "erlang.org": 'Erlang',
    "ethereum.org": 'Ethereum',
    "etsy.com": 'Etsy',
    "evernote.com": 'Evernote',
    "expeditedssl.com": 'ExpeditedSSL',
    
    # F
    "fantasyflightgames.com": 'Fantasy Flight Games',
    "fedex.com": 'FedEx',
    "fedora.org": 'Fedora',
    "figma.com": 'Figma',
    "firefox.com": 'Firefox',
    "first-order.com": 'First Order',
    "firstdraft.com": 'First Draft',
    "flickr.com": 'Flickr',
    "flipboard.com": 'Flipboard',
    "fly.io": 'Fly',
    "fontawesome.com": 'Font Awesome',
    "fonticons.com": 'Fonticons',
    "fortawesome.com": 'Fort Awesome',
    "forumbee.com": 'Forumbee',
    "foursquare.com": 'Foursquare',
    "freecodecamp.org": 'freeCodeCamp',
    "freebsd.org": 'FreeBSD',
    "fulcrum.com": 'Fulcrum',
    
    # G
    "galacticrepublic.com": 'Galactic Republic',
    "galacticsenate.com": 'Galactic Senate',
    "getpocket.com": 'Pocket',
    "gg.com": 'GG',
    "git-scm.com": 'Git',
    "gitkraken.com": 'GitKraken',
    "gitter.im": 'Gitter',
    "glide.com": 'Glide',
    "gofore.com": 'Gofore',
    "goodreads.com": 'Goodreads',
    "google.com/drive": 'Google Drive',
    "google.com/play": 'Google Play',
    "google.com/wallet": 'Google Wallet',
    "gratipay.com": 'Gratipay',
    "gravatar.com": 'Gravatar',
    "gripfire.com": 'Gripfire',
    "gruntjs.com": 'Grunt',
    "gulpjs.com": 'Gulp',
    
    # H
    "hackernews.com": 'Hacker News',
    "hackerrank.com": 'HackerRank',
    "hips.com": 'HIPS',
    "hireahelper.com": 'HireAHelper',
    "hive.io": 'Hive',
    "hooli.com": 'Hooli',
    "hornbill.com": 'Hornbill',
    "hotjar.com": 'Hotjar',
    "houzz.com": 'Houzz',
    "html5.org": 'HTML5',
    "hubspot.com": 'HubSpot',
    
    # I
    "ideal.com": 'iDEAL',
    "innosoft.com": 'Innosoft',
    "instalod.com": 'InstaLOD',
    "intercom.com": 'Intercom',
    "internetexplorer.com": 'Internet Explorer',
    "invision.com": 'InVision',
    "ioxhost.com": 'IoxHost',
    "itch.io": 'itch.io',
    "itunes.com": 'iTunes',
    
    # J
    "java.com": 'Java',
    "jedorder.com": 'Jedi Order',
    "jenkins.io": 'Jenkins',
    "jira.com": 'Jira',
    "joget.com": 'Joget',
    "joomla.org": 'Joomla',
    "js.org": 'JS',
    
    # K
    "kaggle.com": 'Kaggle',
    "keybase.io": 'Keybase',
    "keycdn.com": 'KeyCDN',
    "kickstarter.com": 'Kickstarter',
    "korvue.com": 'Korvue',
    
    # L
    "laravel.com": 'Laravel',
    "last.fm": 'Last.fm',
    "leanpub.com": 'Leanpub',
    "lesscss.org": 'Less',
    "line.me": 'Line',
    "linode.com": 'Linode',
    "linux.org": 'Linux',
    "lyft.com": 'Lyft',
    
    # M
    "magento.com": 'Magento',
    "mailchimp.com": 'Mailchimp',
    "mandalorian.com": 'Mandalorian',
    "markdown.org": 'Markdown',
    "mastodon.social": 'Mastodon',
    "maxcdn.com": 'MaxCDN',
    "mdbootstrap.com": 'MDB',
    "medapps.com": 'MedApps',
    "medium.com": 'Medium',
    "medrt.com": 'MedRT',
    "meetup.com": 'Meetup',
    "megaport.com": 'Megaport',
    "mendeley.com": 'Mendeley',
    "micro.blog": 'Micro.blog',
    "microsoft.com": 'Microsoft',
    "mix.com": 'Mix',
    "mixcloud.com": 'Mixcloud',
    "mixer.com": 'Mixer',
    "mizuni.com": 'Mizuni',
    "modx.com": 'MODX',
    "monero.org": 'Monero',
    
    # N
    "napster.com": 'Napster',
    "neos.io": 'Neos',
    "nimblr.com": 'Nimblr',
    "nodejs.org": 'Node.js',
    "npmjs.com": 'npm',
    "ns8.com": 'NS8',
    "nutritionix.com": 'Nutritionix',
    
    # O
    "octopus.com": 'Octopus Deploy',
    "oldrepublic.com": 'Old Republic',
    "opencart.com": 'OpenCart',
    "openid.net": 'OpenID',
    "optinmonster.com": 'OptinMonster',
    "orcid.org": 'ORCID',
    "opensource.org": 'Open Source Initiative',
    
    # P
    "page4.com": 'Page4',
    "pagelines.com": 'Pagelines',
    "palfed.com": 'PalFed',
    "paypal.com": 'PayPal',
    "penny-arcade.com": 'Penny Arcade',
    "perbyte.com": 'PerByte',
    "periscope.tv": 'Periscope',
    "phabricator.org": 'Phabricator',
    "phoenixframework.org": 'Phoenix Framework',
    "phoenixsquadron.com": 'Phoenix Squadron',
    "php.net": 'PHP',
    "piedpiper.com": 'Pied Piper',
    "playstation.com": 'PlayStation',
    "producthunt.com": 'Product Hunt',
    "pushed.com": 'Pushed',
    "python.org": 'Python',
    
    # Q
    "qq.com": 'QQ',
    "quinscape.com": 'QuinScape',
    "quora.com": 'Quora',
    
    # R
    "r-project.org": 'R Project',
    "raspberrypi.org": 'Raspberry Pi',
    "ravelry.com": 'Ravelry',
    "reactjs.org": 'React',
    "reacteurope.org": 'ReactEurope',
    "readme.io": 'ReadMe',
    "rebel.com": 'Rebel',
    "redhat.com": 'Red Hat',
    "redriver.com": 'Red River',
    "renren.com": 'Renren',
    "replyd.com": 'replyd',
    "researchgate.net": 'ResearchGate',
    "resolving.com": 'Resolving',
    "rev.com": 'Rev',
    "rocket.chat": 'Rocket.Chat',
    "rockrms.com": 'Rock RMS',
    "rust-lang.org": 'Rust',
    
    # S
    "safari.com": 'Safari',
    "salesforce.com": 'Salesforce',
    "sass-lang.com": 'Sass',
    "schlix.com": 'Schlix',
    "scribd.com": 'Scribd',
    "searchengin.com": 'Searchengin',
    "sellcast.com": 'Sellcast',
    "sellsy.com": 'Sellsy',
    "servicestack.com": 'ServiceStack',
    "shirtsinbulk.com": 'Shirts in Bulk',
    "shopify.com": 'Shopify',
    "shopware.com": 'Shopware',
    "simplybuilt.com": 'SimplyBuilt',
    "sistrix.com": 'SISTRIX',
    "sith.com": 'Sith',
    "sketch.com": 'Sketch',
    "skyatlas.com": 'Skyatlas',
    "slideshare.net": 'SlideShare',
    "sourcetree.com": 'Sourcetree',
    "speakap.com": 'Speakap',
    "speakerdeck.com": 'Speaker Deck',
    "squarespace.com": 'Squarespace',
    "stackpath.com": 'StackPath',
    "staylinked.com": 'StayLinked',
    "stickermule.com": 'Sticker Mule',
    "strava.com": 'Strava',
    "stripe.com": 'Stripe',
    "studiovinari.com": 'Studio Vinari',
    "stumbleupon.com": 'StumbleUpon',
    "superpowers.com": 'Superpowers',
    "supple.com": 'Supple',
    "suse.com": 'SUSE',
    "swift.org": 'Swift',
    "symfony.com": 'Symfony',
    
    # T
    "teamspeak.com": 'TeamSpeak',
    "tencent.com": 'Tencent Weibo',
    "theredyeti.com": 'The Red Yeti',
    "themeco.com": 'Themeco',
    "themeisle.com": 'ThemeIsle',
    "thinkpeaks.com": 'Think Peaks',
    "tiktok.com": 'TikTok',
    "trade-federation.com": 'Trade Federation',
    "tripadvisor.com": 'TripAdvisor',
    "typo3.org": 'TYPO3',
    
    # U
    "uber.com": 'Uber',
    "ubuntu.com": 'Ubuntu',
    "uikit.com": 'UIkit',
    "umbraco.com": 'Umbraco',
    "uncharted.com": 'Uncharted',
    "uniregistry.com": 'Uniregistry',
    "unity.com": 'Unity',
    "unsplash.com": 'Unsplash',
    "untappd.com": 'Untappd',
    "ups.com": 'UPS',
    "usb.org": 'USB',
    "usps.com": 'USPS',
    "ussunnah.com": 'US Sunnah',
    
    # V
    "vaadin.com": 'Vaadin',
    "viacoin.com": 'Viacoin',
    "viadeo.com": 'Viadeo',
    "viber.com": 'Viber',
    "vine.co": 'Vine',
    "vnv.com": 'VNV',
    "vuejs.org": 'Vue.js',
    
    # W
    "watchman-monitoring.com": 'Watchman Monitoring',
    "waze.com": 'Waze',
    "weebly.com": 'Weebly',
    "weibo.com": 'Weibo',
    "weixin.qq.com": 'Weixin',
    "whmcs.com": 'WHMCS',
    "wikipedia.org": 'Wikipedia',
    "wix.com": 'Wix',
    "wizardsofthecoast.com": 'Wizards of the Coast',
    "wolfpackbattalion.com": 'Wolf Pack Battalion',
    "wordpress.org": 'WordPress',
    "wpbeginner.com": 'WPBeginner',
    "wpexplorer.com": 'WPExplorer',
    "wpforms.com": 'WPForms',
    "wpressr.com": 'WPpressr',
    "xbox.com": 'Xbox',
    "xing.com": 'XING',
    
    # Y
    "ycombinator.com": 'Y Combinator',
    "yammer.com": 'Yammer',
    "yandex.com": 'Yandex',
    "yarnpkg.com": 'Yarn',
    "yelp.com": 'Yelp',
    "yoast.com": 'Yoast',
    "youtube.com": 'YouTube',
    
    # Z
    "zhihu.com": 'Zhihu',
}